version: 2
env:
  - GOTOOLCHAIN=go1.27.1
builds:
  - main: ./client
    id: "ss5-client"
    binary: ss5-client
    goos:
      - linux
      - darwin
      - windows

  - main: ./server
    id: "ss5-server"
    binary: ss5-server
    goos:
      - linux
      - darwin
      - windows
archives:
  - id: my-archive

    formats:
      - tar.gz

    ids:
      - ss5-server
      - ss5-client

    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

    wrap_in_directory: true

    format_overrides:
      - goos: windows
        formats:
          - zip

    files:
      - .ss5-client.json
      - .ss5-server.json
      - ss5-client.service
      - ss5-server.service
      - README.md
      - LICENSE

release:
  github:
    owner: Leviathan0992
    name: ss5

  draft: false

  prerelease: false

  header: |
    ## ss5 {{ .Tag }}

  disable: false
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
